# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.boot_timeout = 400
	config.vm.synced_folder "shared", "/shared"
		
	config.vm.define "master" do |master|
		master.vm.hostname = "dictator.qac.local"
		master.vm.box = "chad-thompson/ubuntu-trusty64-gui"
		master.vm.network :public_network, :public_network => "wlan0", ip: "192.168.1.98"
		master.vm.provision :shell, path: "bootstrap_master.sh"
		master.vm.provider :virtualbox do |masterVM|
			masterVM.gui = true
			masterVM.name = "dictator"
			masterVM.memory = 4096
			masterVM.cpus = 2
		end
	end
end

